packages/react-percy-storybook/src/react-percy-storybook.d.ts
Before, it was possible to pass an undefined `storyFn`.
=> fix: clean up optional parameters signature

.travis.yml, scripts/run-integration-tests.sh
Summary
--
Upgrade to Yarn v1 in CI and get rid of the linking in integration tests now that Yarn properly maps bin files in lerna projects.
=> Upgrade Yarn to 1.0.1

integration-tests/storybook-for-react/stories/index.js, integration-tests/storybook-for-vue/stories/index.js, packages/percy-storybook/src/__tests__/selectStories-tests.js, packages/percy-storybook/src/percy-storybook.d.ts, packages/percy-storybook/src/selectStories.js
This adds an option skip option to addWithPercyOptions, which excludes the story from tests. It overrides any other options for the story.
Fixes #15
=> Add skip option to addWithPercyOptions

packages/percy-storybook/src/__tests__/getRtlRegex-tests.js, packages/percy-storybook/src/getRtlRegex.js
We had a bug where using the g flag in the rtl regex was making the regex sticky, and causing matches on subsequent names that were shorter to fail.  
The result was some RTL stories were being skipped when the --rtl option was being used.
=> Fix rtl regex

packages/percy-storybook/src/__tests__/getStaticAssets-tests.js, packages/percy-storybook/src/getStaticAssets.js
This fixes a problem with a change introduced in Storybook 3.3.
Thanks @joscha for the heads up!
Fixes #23
=> Fix regex for parsing preview as last script on a single line

packages/percy-storybook/src/__tests__/getStories-tests.js, packages/percy-storybook/src/getStories.js
We have a customer who's calling fetch() before calling serializeStories, which is resulting in the stories to be set on the window a second or two after the jsDOM done callback gets called.
This PR allows 10 seconds for the stories to be set, before returning a failure.
You can test this works by updating the [serializeStories call in one of our integration tests](https://github.com/percy/percy-storybook/blob/master/integration-tests/storybook-for-react/storybook/config.js#L38) to `fetch('https://example.com').then(serializeStories(getStorybook));` and then running `storybook:percy`.
Without this PR, it fails.  With the PR, it succeeds.
=> Allow 10 seconds for stories to be set on window.

integration-tests/storybook-for-react/package.json, integration-tests/storybook-for-react/stories/index.js, packages/percy-storybook/src/__tests__/getStaticAssets-tests.js, packages/percy-storybook/src/__tests__/getStories-tests.js, packages/percy-storybook/src/cli.js, packages/percy-storybook/src/getStaticAssets.js, packages/percy-storybook/src/getStories.js, yarn.lock
Storybook previously created one javascript file, static/preview-xxx.js, which could be executed to retrieve all of the story names.
Storybook 4.0 introduces code-splitting, so multiple static/*.js files need to be executed in order to retrieve all of the story names.
I've updated the React integration tests to use Storybook 4.0, and have left the Vue and Angular ones at 3.4.
=>  Handle Storybook 4.0 code-splitting preview.js into multiple js files

integration-tests/storybook-for-react/stories/index.js, packages/percy-storybook/package.json, yarn.lock
When a story name includes double quotes, it works correctly in Storybook itself, but causes a problem with percy-storybook.
This is because the conversion of the story name to a resource url isn't correctly sanitizing the name.  It needs to either strip the quotes and other characters, or not use the name for the url.  This is the line of code where it happens: https://github.com/percy/react-percy/blob/master/packages/react-percy-api-client/src/resources/makeRootResource.js#L4
The slugify package does have an option to remove characters, if we decide to go that route: https://www.npmjs.com/package/slugify
=> Sanitize Storynames

.travis.yml, HOWITWORKS.md, packages/percy-storybook/package.json, packages/percy-storybook/src/cli.js, yarn.lock
Simple PR to upgrade `react-percy-api-client` and remove references to PERCY_PROJECT
=> Update react percy api client

integration-tests/storybook-for-ember/package-lock.json, integration-tests/storybook-for-ember/package.json
Resolves the [handlebars 2.0 security alert](https://github.com/percy/percy-storybook/network/alert/integration-tests/storybook-for-ember/package.json/handlebars/open) surfaced by GitHub.
=> Upgrade handlebars version used in ember integration test

.travis.yml, appveyor.yml, integration-tests/storybook-for-react/package.json
Ensures our Storybook SDK is ready for the upcoming Storybook 4.1 release.
It also abandons running unit tests in nodejs v6 and adds them for v10.  The majority of tests are in nodejs v8.
Nodejs v6 abandonment was due to one of the upgraded sub-dependencies requiring engine 8.
=> Upgrade to Storybook 4.1.0-alpha.10 in React integration test

integration-tests/storybook-for-react/stories/index.js, packages/percy-storybook/src/__tests__/getStories-tests.js, packages/percy-storybook/src/__tests__/iframe.html, packages/percy-storybook/src/constants.js, packages/percy-storybook/src/getStories.js
This avoids problems of page.evaluate returning undefined if some of the other story attributes can't be serialized.  ie. when the info for a story contains a jsx fragment.
=> Filter to only relevant attributes when fetching story attributes.

packages/percy-storybook/src/args.js, packages/percy-storybook/src/cli.js
About three days ago we upgrade to Storybook v5, unfortunately we didn't notice that the Storybook package didn't correctly pick up the stories any more:
This introduces a new CLI flag `--fail_on_empty` which will make `percy-storybook` throw if the stories could not be found.
jest and other unit testing tools fail if their test suite is empty by default (see https://github.com/facebook/jest/issues/6451) for that reason. I personally think this is how Percy should behave as well, but it is theoretically a backwards-incompatible change, so I made the newly introduced flag false by default. Let me know if you are happy to make this a breaking change and I will update the PR.
cc @diagramatics @kongakong
=> feat: fail when no stories are found

packages/percy-storybook/src/cli.js
Even though the tests passed for #130, when merged they failed (for a good reason). Looks like yargs wants the default values to be strings rather than any other types. This PR fixes that
=> fix: Yargs wants flags to be strings

packages/percy-storybook/src/getStories.js, packages/percy-storybook/src/selectStories.js
The `selectedKind` and `selectedStory` params are a legacy format that has issues when parameters are url-encoded. Fallback to legacy is still supported.
[Relevant comment from Storybook source](https://github.com/storybookjs/storybook/blob/5c43d0cb449845d5211870a16a141881869cd3a1/lib/core/src/client/preview/url.js#L30-L31)
Fixes #164
Use and prefer `story.id` when storing params for selected stories. If not present, the legacy query format is still used.
There is already a test for this. It is currently failing for new PRs. As long as all visual tests pass, this fix is verified to work.
=> fix: Use story id for query format if possible

src/selectStories.js, tests/integration/storybook-for-react/stories/index.js
This encodes any URLs we're passing to the API to remove any special chars that might be rejected.
=> fix: Encode old url to prevent issues with emojis

src/commands/storybook/start.js, test/storybook-start.test.js
When using `percy storybook:start` we don't want `start-storybook` to open the storybook in a browser or prompt for user input. This adds the `--ci` flag by default to avoid those things.
=> ✨ Automatically add start-storybook --ci arg

README.md
Adds a small paragraph directly under the upgrade install command that mentions replacing existing usage with new usage. 
Also rewords the breaking changes intro since the recommended upgrade path is to just replace your existing usage. In addition to the rewording, the command change is also listed.
=> 📝 Refine readme upgrade section

README.md
Previous versions of this SDK had a default, flag controlled, minimum height of 800px. In all other SDKs (and now the latest version of this SDK) the default minimum height is handled by the API and our rendering environment, which is set to 1024px. When upgrading and relying on defaults, users may experience height related diffs. This change should be pointed out in the breaking changes section of the readme so people can be informed of the height difference.
=> 📝 Add default min height to breaking changes

package.json, src/command.js, src/commands/storybook/index.js, src/commands/storybook/start.js, test/.storybook/args.stories.js, test/.storybook/deprecated.stories.js, test/.storybook/main.js, test/storybook-start.test.js, test/storybook.test.js, yarn.lock
`@percy/core` has some nice recent changes to the internal queue that we need to account for here.
- First, rather than mapping and awaiting on captures, we can synchronously queue them with the improved snapshot method. When `percy.stop()` is eventually called via `finally()`, it will wait for all queued snapshots. When called with an error, it will dequeue all snapshots and attempt to finalize any build immediately.
- The `client.sendSnapshot()` patch needed to be updated to account for a `buildId` parameter.
- Now that the `percy.capture()` method has been merged with `percy.snapshot()`, we should remove a couple of options that could potentially cause issues if provided. Mainly, the `domSnapshot` and `execute` options. We could potentially allow `execute`, but I think it may be …
=> ♻️ Update code to accommodate core changes

src/config.js, src/hooks/init.js, test/storybook.test.js
The deprecated `snapshots` option (now `additionalSnapshots`) no longer needs to hang around now that we're on a stable release.
=> 🔇 Remove deprecated `snapshots` option & logs

src/command.js, test/storybook.test.js
Currently we're not collecting the version of Storybook when creating builds. This makes it a little harder to provide support (and becomes a question to the customer rather than us just having it). 
The version is missing from v4 because how we gathered the version in the past was a bit cumbersome. It would look at the dependency tree and try to match a storybook framework version. There's no single package for us to import to get the version from. 
The way we grab the version now is by visiting the `?path=/settings/about` route and plucking the version from the DOM. Storybook uses this route to show the current version & does a version check. 
A small improvement was made to how we get gather the stories off of the `window` object. We now use the `waitFor` util to double check the var …
=> 🐛 Gather Storybook version for SDK UA

.github/workflows/test.yml, package.json, src/common.js, src/snapshots.js, src/start.js, src/storybook.js, src/utils.js, test/.storybook/mixed.stories.js, test/storybook-start.test.js, test/storybook.test.js, yarn.lock
With #592, it was discovered that this SDK was actually missing quite a bit of tests. Since it was out of scope for that PR, we opted to address this in another PR (this PR).
With the addition of new tests to achieve 100% coverage, a few small bugs inevitably came up and were fixed.
- When splitting snapshots into shards with `--shard-count`, providing the `--partial` flag will now always set the parallel total environment variable to `-1` unless already set. Previously, the `--shard-count` flag did not consider the `--partial` flag when setting the environment variable.
- When creating the story URL and settings params with the native URLSearchParams API, it will encode any provided values. However, args and globals params are already encoded, therefore resulting in double encoding of …
=> 🐛 Add missing tests and miscellaneous fixes

package.json, src/snapshots.js, src/utils.js, test/.storybook/args.stories.js, test/storybook.test.js, test/unit.test.js, yarn.lock
We need to be able to recreate acceptable Storybook query params for args and globals when generating a story's URL. To do this, we have historically relied on Storybook's own internal utils to ensure 1:1 compatibility.
Unfortunately, this dependency has proven to be highly volatile. Early minor updates had the util moving between files, while other updates effected the package's build output. Most recently, The package's distributed files have become tightly bundled to React. While this doesn't present a problem when used within a React Storybook project, it does however cause dependency errors when used outside of React environments (even when the target Storybook is using React).
With these changes, we no longer depend on a Storybook internal package, and instead reimplement and …
=> ♻️ Remove dependency on storybook param util

package.json, src/snapshots.js, src/utils.js, test/storybook-start.test.js, test/storybook.test.js, yarn.lock
Currently, `Ctrl+C` or normal kill signals do not work to stop the Storybook SDK process from running. This is because the majority of the work is done in promises, which block CLI's abort handling.
This PR fixes this issue by updating `@percy/cli-command` and refactoring a few promises utilizing new generator utils.
=> 🐛 Fix process aborting

package.json, src/config.js, src/snapshots.js, test/storybook.test.js, yarn.lock
This PR fixes #621 by utilizing validation helpers to scrub unused snapshot options without warning about them. A test was adjusted slightly to ensure the warnings are no longer logged when capture options such as `waitForSelector` are provided.
While making this change, I realized that these capture options are not actually used at all when JavaScript is enabled. This is intended since enabling JavaScript tells this SDK to use the raw preview DOM to avoid rehydration issues. But it may be confusing if some people expect these options to work when they won't be used at all. 
To address this confusion, the config schema was refactored to validate against capture options when JavaScript is enabled. This required a couple small upstream changes and a much more complex schema for this SDK. …
=> 🐛 Fix capture options validation warnings

src/snapshots.js
A few internal core methods will be changing in the next CLI update and will require some changes to this SDK for it to continue working correctly. These changes can be made preemptively before the next CLI release since they will continue to work with older CLI versions.
=> 🐛 Preemptively update usage of internal core methods

.github/workflows/test.yml, package.json, src/config.js, test/.storybook/snapshot.stories.js, test/storybook.test.js, yarn.lock
goes after https://github.com/percy/cli/pull/1238
* Post CLI release is done which adds support for `domTransformation` flag, we'll update CLI dependency in this package. 
* `snapshotSchema` is already included in `storybookSchema` so no additional configuration is required. 
* This PR only updates dependency and adds tests.
Eg: something like below which will make the image eager loading in asset discovery browser. This can be part of storybook's config
This can be provided in percy story config(as done in the test case) or global `preview.js` config
```js
percy: {
domTransformation: '(documentElement) => { documentElement.querySelectorAll("img").forEach(img => img.setAttribute("src", img.getAttribute("data-src")));  }',
}
````
=> ✨ add support for domTransformation

src/snapshots.js, test/storybook.test.js
Context:
- Currently if percySnapshot fails on one of the stories [ say dom.js returned an exception or timedout ] we throw that error again
- This breaks test suite and no further stories are uploaded
Change:
- We add an env var `PERCY_SKIP_STORY_ON_ERROR` which if set to 'true' would log the error skip the story and move to next story 
- We also recreate the page to avoid any state related issues
=> ✨  Skip story on error and move to next stories

src/snapshots.js, src/utils.js, test/storybook.test.js
=> 🐛 ✨Fix eval setCurrentStory error + make logging better

src/utils.js
**context -**
- we have added support for capturing service worker intercepted requests in https://github.com/percy/cli/pull/1443
- in msw, it checks if service worker controller is registered or not. If it is not registered then it goes into an infinite rendering loop.
- when using percy browser, by default we have `setByPassServiceWorker: false` which does not allow registration of service worker controller and hence we go in infinite rendering loop.
- adding `captureServiceWorker: true` enables us to register service worker controller, and hence resolves the infinite rendering loop.
=> feat: add captureServiceWorker flag when opening browser

README.md, package.json
Making storybook integration
Readme Update
=> Making storybook addons integration

CRONTRIBUTING.md
Added contributing file so that open source contributors have some guidelines while creating PRs
=> Added CRONTRIBUTING file

src/snapshots.js, src/utils.js, test/storybook.test.js
- Adding retry in withPage function.
- Update evalSetCurrentStory swap:  `setCurrentStory` & `updateGlobals`.
Above changes are with respect to storybook v8 fixes, we were getting `execution context destroyed` on several stories. swapping above calls fixes this.
=> Add retry in withPage function

src/snapshots.js, test/.storybook/snapshot.stories.js, test/storybook.test.js
Fixed behaviour of enable javascript where if percy.config.snapshot.enableJavascript is true and options.enableJavascript is false. sdk is going through enableJS flow. ideally it should use snapshot level option if passed over global options
=> Change behaviour of enable JS to prioritise options passed

src/snapshots.js, src/utils.js, test/storybook.test.js
updating error message and fixing retry snapshot bug
=> updating error message and fixing retry snapshot bug

package.json, src/utils.js, test/utils.test.js
- Beta release of Responsive Snapshot Capture in Storybook SDK
> - Introduced support for responsive DOM capture, allowing snapshots across multiple viewport widths
> 
> - This is a beta release of the responsive snapshot functionality
> 
> - Renamed environment variable from `PERCY_RESPONSIVE_CAPTURE_SLEEP_TIME` to `RESPONSIVE_CAPTURE_SLEEP_TIME`
> 
> - This change was made to align with the Selenium SDK, where the variable already existed without the PERCY_ prefix
> 
> Helps maintain consistency across SDKs and avoids unnecessary prefixing specific to Storybook
https://www.browserstack.com/docs/percy/get-started/set-env-var#Percy_SDK
=> Release 9.0.0 beta.1

src/snapshots.js, src/utils.js, test/snapshots.test.js, test/utils.test.js
When the `PERCY_RESPONSIVE_CAPTURE_RELOAD_PAGE` flag was enabled, some snapshots were coming out **blank or stuck on loaders**.
This happened because:
*   We reloaded the page after resizing, but did not wait for the story to fully load again and for the loaders to disappear.
*   The URL from `window.location.href` didn't include story-specific params (like `globals`, `args`, `viewMode`), so the reloaded story lost its state.
*   Instead of using `window.location.href`, we now build the full URL directly from `story.url`.
*   This ensures `viewMode=story` and all story params (`globals`, `args`) are included.
```js
await page.eval(evalSetCurrentStory, story);
```
*   Guarantees that after reload, the story is restored with the correct state (e.g., dark mode, args, globals).
*   Also …
=> Fix: Preserve story state & prevent blank/loader snapshots after reload
