- appveyor.yml
Run tests on Appveyor's Windows CI
> Windows CI

- packages/percy-storybook/src/__tests__/getStaticAssets-tests.js
- packages/percy-storybook/src/getStaticAssets.js
> Tolerate type attribute in script tag

- packages/percy-storybook/src/__tests__/getMinimumHeight-tests.js
- packages/percy-storybook/src/__tests__/getOutputFormat-tests.js
- packages/percy-storybook/src/args.js
- packages/percy-storybook/src/cli.js
- packages/percy-storybook/src/getOutputFormat.js
- packages/percy-storybook/src/getStaticAssets.js
- packages/percy-storybook/src/uploadStorybook.js
Thanks @joscha for doing the majority of the work here in https://github.com/percy/percy-storybook/pull/19.
Also includes a fix for https://github.com/percy/percy-storybook/issues/20.
> Add output_format arg, that provides for JSON output of build status

- .travis.yml
This prevents travis from running twice for every commit pushed to a PR.
> Travis config - only run tests on PRs and master

- integration-tests/storybook-for-react/stories/index.js
- packages/percy-storybook/src/selectStories.js
- packages/percy-storybook/src/uploadStory.js
Big thank you to @miguelyoobic95 for taking this on and doing the work. This PR adds the ability to configure per-story min-heights (rather than just a global CLI option).
> feat: Allow per-story min-height config

- .travis.yml
- appveyor.yml
- packages/percy-storybook/package.json
_Potentially breaking release_, so tagged as a feature in case users need to pin to an older version rather than update unmaintained node
> feat: Use node v10

- README.md
It's not super obvious these are regex's on the story name (so lets make it)
> 📝  Update README `include` & `exclude` docs

- .github/workflows/release.yml
- README.md
This updates the README to remove the `@next` install instructions and also removes the `--next` flag from the release script.
> 🔧 Update README & release script for stable release

- package.json
>  🔖 chore: bump package version to 5.0.0

- package.json
> Releasing 5.0.2

- README.md
- package.json
adding test keyword and adding utm to links
> adding test keyword and adding utm to links

- package.json
- packageV7.json
Releasing Storybook v8 support in GA
> release v6.0.0

- package.json
- packageV7.json
> Release v6.0.1 stable version

- package.json
- packageV7.json
> Releasing v6.0.2-beta.0

- package.json
- packageV7.json
> release-v6.0.2

- package.json
- packageV7.json
> release v6.0.3

- package.json
- packageV6.json
- packageV7.json
- test/storybook.test.js
Description
Fixed test cases for master cli v1.30.7
> fixing test cases

- package.json
- packageV7.json
Fixed test cases for master cli v1.30.7
> Changed version to v6.0.4-beta.0

- package.json
> 🔖 Release v7.0.0

- src/snapshots.js
- src/utils.js
- test/storybook.test.js
This pull request refactors the snapshot processing logic for Storybook integration, focusing on improved error handling and robustness when capturing story snapshots. The main changes include extracting story processing into a dedicated function, enhancing the handling of execution context destruction errors, and updating related utility and test code to align with the new error management approach.
**Snapshot processing and error handling improvements:**
* Introduced a new `processStory` async generator function in `src/snapshots.js` to encapsulate the logic for processing individual stories and capturing their DOM snapshots, improving code organization and readability.
* Refactored the main snapshot processing loop in `takeStorybookSnapshots` to use the new `processStory` function and …
> Refactor snapshot handling to improve error management and processing efficiency

- package.json
> Release-9.0.1-beta.1

- package.json
> 🔖 Release v9.1.0
